config/routes.rb
Rails.application.routes.draw do
  # Routes for the Pet resource:

  # Creates all the seven CRUD routes that are most commonly used
  resources :pets

  # # CREATE
  # post("/pets", { :controller => "pets", :action => "create" })
          
  # # READ
  # get("/pets", { :controller => "pets", :action => "index" })
  
  # get("/pets/new", { :controller => "pets", :action => "new" })
  # get("/pets/:id", { :controller => "pets", :action => "show" })
  
  # # UPDATE
  
  # patch("/pets/:id", { :controller => "pets", :action => "update" })
  # get("/pets/:id/edit", { :controller => "pets", :action => "edit" })
  
  # # DELETE
  # delete("/pets/:id", { :controller => "pets", :action => "destroy" })

  #------------------------------

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true, numericality: { greater_than: -1, less_than: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :edit, :destroy, :update]

  def set_pet
    @pet = Pet.find(params.fetch("id"))
  end

  def new
    @pet = Pet.new
  end

  def edit
    @pet = Pet.find(params.fetch("id"))
  end

  def index
    matching_pets = Pet.all

    @list_of_pets = matching_pets.order({ :created_at => :desc })
    

    respond_to do |format|
      # Implicitly happening
      
      format.html do
        render("pets/index.html.erb")
      end

      format.json do 
        render json: @list_of_pets
      end

    end




    # render({ :template => "pets/index.html.erb" })
  end

  def show
    # the_id = params.fetch("path_id")

    # matching_pets = Pet.where( id: the_id )

    # @the_pet = matching_pets[0]

    # adding ! throws "Record not found" error if id doesn't exist in db
    @pet = Pet.find( params.fetch("id") )


    # Assumes you are referencing an html page so adding html.erb path isn't necessary
    # render({ :tmeplate => "pets/show.html.erb"})

    # render template: "pets/show"
    
    # render("pets/show")

    # render("show")

    # Render statements are not necessary if the controller method matches name of view page

  end

  def create
    # @pet = Pet.new
    # @pet.name = params.fetch(:name)
    # @pet.age = params.fetch(:age)
    # @pet.species_id = params.fetch(:species_id)

    pet_params = params.require(:pet_attributes).permit(:age, :name, :species_id)
    @pet = Pet.new(pet_params)

    if @pet.valid?
      @pet.save
      redirect_to("/pets", { :notice => "Pet created successfully." })
    else
      # redirect_to("/pets/new", { :alert => @pet.errors.full_messages.to_sentence })

      render("new")
    end
  end

  def update
    # the_id = params.fetch("path_id")
    # @pet = Pet.find(params.fetch("id"))

    # @pet.name = params.fetch("query_name")
    # @pet.age = params.fetch("query_age")
    # @pet.species_id = params.fetch("query_species_id")

    pet_params = params.require(:pet).permit(:age, :name, :species_id)

    @pet.update(pet_params)

    if @pet.valid?
      @pet.save
      redirect_to("/pets/#{@pet.id}", { :notice => "Pet updated successfully."} )
    else
      render("edit")
    end
  end

  def destroy
    # the_id = params.fetch("path_id")
    @pet = Pet.find(params.fetch("id"))

    @pet.destroy

    redirect_to("/pets", { :notice => "Pet deleted successfully."} )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VanillaRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color: green;"><%= notice %></p>
    <p style="color: red;"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pets/_pet_form.html.erb
<%= form_with model: @pet do |form| %>
    <div>
        <%# <label for="name_box">
          Name
        </label> %>

        <%= form.label :name %>

        <%# <input type="text" id="name_box" name="query_name" value="<%= @pet.name %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%# <label for="age">
          Age
        </label> %>

        <%= form.label :age %>

        <%= form.text_field :age%>
        <%# <input type="text" id="age" name="age" value="<%= @pet.age %>
      </div>

      <div>
        <%# <label for="species_id_box">
          Species
        </label> %>

        <%= label_tag :species_id %>

        <%# <input type="text" id="species_id_box" name="query_species_id"> %>
        <%= text_field_tag :species_id %>
      </div>

      <%= form.submit %>
    </form>
  
 <% end %>

app/views/pets/edit.html.erb
<div>
  <div>
    <h2>
      Edit pet
    </h2>

     <% @pet.errors.full_messages do |error| %>
      <p><%= error %></p>
    <% end %>

     <%= form_with model: @pet do |form| %>
      <div>
          <%# <label for="name_box">
            Name
          </label> %>

          <%= form.label :name %>

          <%# <input type="text" id="name_box" name="query_name" value="<%= @pet.name %>
          <%= form.text_field :name %>
        </div>

        <div>
          <%# <label for="age">
            Age
          </label> %>

          <%= form.label :age %>

          <%= form.text_field :age%>
          <%# <input type="text" id="age" name="age" value="<%= @pet.age %>
        </div>

        <div>
          <%# <label for="species_id_box">
            Species
          </label> %>

          <%= label_tag :species_id %>

          <%# <input type="text" id="species_id_box" name="query_species_id"> %>
          <%= text_field_tag :species_id %>
        </div>

        <%= form.submit "Update pet" %>
      </form>
    <% end %>

    <hr>
    <hr>
    <form action="/pets/<%= @pet.id %>"  method="post" >

      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

      <%# For creating Patch CRUD operations %>
      <input type="hidden" name="_method" value="patch" >

      <div>
        <label for="name_box">
          Name
        </label>

        <input type="text" id="name_box" name="query_name" value="<%= @pet.name %>">
      </div>

      <div>
        <label for="age_box">
          Age
        </label>

        <input type="text" id="age_box" name="query_age" value="<%= @pet.age %>">
      </div>

      <div>
        <label for="species_id_box">
          Species
        </label>

        <input type="text" id="species_id_box" name="query_species_id" value="<%= @pet.species_id %>">
      </div>

      <button>
        Update pet
      </button>
    </form>
  </div>
</div>

app/views/pets/index.html.erb
<div>
  <div>
    <h1>
      List of all pets
    </h1>
  </div>
</div>
<div>
  <a href="/pets/new">Create new pet</a>
</div>
<div>
  <div>
    <table border="1">
      <tr>
        <th>
          ID
        </th>

        <th>
          Name
        </th>

        <th>
          Age
        </th>

        <th>
          Species
        </th>

        <th>
          Created at
        </th>

        <th>
          Updated at
        </th>

        <th>
        </th>
      </tr>

      <% @list_of_pets.each do |a_pet| %>
      <tr>
        <td>
          <%= a_pet.id %>
        </td>

        <td>
          <%= a_pet.name %>
        </td>

        <td>
          <%= a_pet.age %>
        </td>

        <td>
          <%= a_pet.species_id %>
        </td>

        <td>
          <%= time_ago_in_words(a_pet.created_at) %> ago
        </td>
        <td>
          <%= time_ago_in_words(a_pet.updated_at) %> ago
        </td>

        <td>
          <a href="/pets/<%= a_pet.id %>">
            Show details
          </a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<hr>

app/views/pets/new.html.erb
<div>
  <div>
    <h2>
      Add a new pet
    </h2>
    <%= render "pets/pet_form" %>
  </div>
</div>

app/views/pets/show.html.erb
<div>
  <div>
    <h1>
      Pet #<%= @pet.id %> details
    </h1>

    <div>
      <div>
        <%# <a href="/pets">
          Go back
        </a> %>
        <%= link_to "Go back", pets_path %>
      </div>

      <div>
      <%# Rails reserves "data-method=delete" b/c HTML doesn't support delete method  %>
      <%# data: {confirm} creates an alert to confirm the action being taken %>
        <%= link_to "Delete pet", pet_path(@pet.id), method: :delete, data: { confirm: "Are you sure?"} %>
      </div>
    </div>

    <div>
      
      <%= link_to "Edit pet", edit_pet_path(@pet) %>
    </div>

    <dl>
      <dt>
        Name
      </dt>
      <dd>
        <%= @pet.name %>
      </dd>

      <dt>
        Age
      </dt>
      <dd>
        <%= @pet.age %>
      </dd>

      <dt>
        Species
      </dt>
      <dd>
        <%= @pet.species_id %>
      </dd>

      <dt>
        Created at
      </dt>
      <dd>
        <%= time_ago_in_words(@pet.created_at) %> ago
      </dd>

      <dt>
        Updated at
      </dt>
      <dd>
        <%= time_ago_in_words(@pet.updated_at) %> ago
      </dd>
    </dl>
  </div>
</div>